/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/pylon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pylon Webhook
         * @description Check the HMAC, store the ticket, queue its run. Returns fast: Pylon retries slow calls.
         */
        post: operations["pylon_webhook_webhooks_pylon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pipeline */
        get: operations["get_pipeline_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_tickets__ticket_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_tickets__ticket_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Stored events first, then live ones (Postgres LISTEN/NOTIFY). With ?replay=1, re-sends a
         *     stored run at its original pace (gaps capped at 3 s) and closes: no model or tool calls.
         */
        get: operations["stream_events_tickets__ticket_id__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Simulator Templates */
        get: operations["simulator_templates_simulator_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulator Send
         * @description Send a signed ticket through the real webhook, exactly as Pylon would.
         */
        post: operations["simulator_send_simulator_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/scorecard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scorecard */
        get: operations["scorecard_evals_scorecard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalDecision */
        ApprovalDecision: {
            /**
             * Approved
             * @default true
             */
            approved: boolean;
            /** Edited Reply */
            edited_reply?: string | null;
            /** Reviewer */
            reviewer?: string | null;
        };
        /** ApprovalRequiredEvent */
        ApprovalRequiredEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "approval_required";
            /**
             * Stage
             * @default approve
             */
            stage: string;
            /** Draft Reply */
            draft_reply: string;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Linear Issue */
            linear_issue?: string | null;
        };
        /** CodeOut */
        CodeOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "code";
            /** File */
            file: string;
            /** Language */
            language: string;
            /**
             * Start Line
             * @default 1
             */
            start_line: number;
            /** Code */
            code: string;
            /**
             * Highlight
             * @default []
             */
            highlight: number[];
        };
        /** CommitOut */
        CommitOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "commit";
            /** Sha */
            sha: string;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Date */
            date?: string | null;
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /**
         * DeliveryEvent
         * @description A durable receipt for an external handoff or its local logged fallback.
         */
        DeliveryEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "delivery";
            /** Stage */
            stage: string;
            /**
             * Destination
             * @enum {string}
             */
            destination: "linear" | "pylon_reply" | "pylon_note";
            /**
             * Status
             * @enum {string}
             */
            status: "sent" | "logged";
            /** External Id */
            external_id?: string | null;
            /** Detail */
            detail: string;
        };
        /** DiffOut */
        DiffOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "diff";
            /** File */
            file?: string | null;
            /** From Ref */
            from_ref?: string | null;
            /** To Ref */
            to_ref?: string | null;
            /** Diff */
            diff: string;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "error";
            /** Stage */
            stage?: string | null;
            /** Message */
            message: string;
            /** Traceback */
            traceback?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JevAnswer */
        JevAnswer: {
            /** Question */
            question: string;
            /** Answer */
            answer: string | number | boolean;
            /** Confidence */
            confidence: number;
        };
        /** JevEvent */
        JevEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "jev";
            /** Stage */
            stage: string;
            /** Answers */
            answers: components["schemas"]["JevAnswer"][];
            /**
             * Source
             * @default llm
             * @enum {string}
             */
            source: "jev" | "llm" | "llm_fallback" | "stub";
        };
        /** JsonOut */
        JsonOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "json";
            /** Data */
            data: unknown;
        };
        /** LinkEvent */
        LinkEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "link";
            /** Stage */
            stage: string;
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** LogOut */
        LogOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "log";
            /** Source */
            source: string;
            /** Lines */
            lines: string[];
        };
        /** ModelDeltaEvent */
        ModelDeltaEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "model_delta";
            /** Stage */
            stage: string;
            /** Text */
            text: string;
        };
        /**
         * ModelOutputEvent
         * @description A typed result such as Enrichment or Verdict.
         */
        ModelOutputEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "model_output";
            /** Stage */
            stage: string;
            /** Name */
            name: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Model */
            model?: string | null;
            /** Cost Usd */
            cost_usd?: number | null;
        };
        /**
         * OutcomeEvent
         * @description Final ticket result, suitable for the ticket detail and a terminal SSE event.
         */
        OutcomeEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "outcome";
            /**
             * Stage
             * @default complete
             * @constant
             */
            stage: "complete";
            /** Lane */
            lane?: string | null;
            /** Summary */
            summary: string;
            /** Verdict Kind */
            verdict_kind?: string | null;
            /** Root Cause */
            root_cause?: string | null;
            /** Service */
            service?: string | null;
            /** File Line */
            file_line?: string | null;
            /** Commit */
            commit?: string | null;
            /** Duplicate Of */
            duplicate_of?: string | null;
            /** Linear Issue */
            linear_issue?: string | null;
            /**
             * Engineering Handoff
             * @default not_needed
             * @enum {string}
             */
            engineering_handoff: "created" | "local_only" | "not_needed";
            /** Reply */
            reply?: string | null;
            /**
             * Reply Delivery
             * @default not_sent
             * @enum {string}
             */
            reply_delivery: "sent" | "logged" | "not_sent";
            /** Approved */
            approved?: boolean | null;
        };
        /** Pipeline */
        Pipeline: {
            /** Nodes */
            nodes: components["schemas"]["PipelineNode"][];
            /** Edges */
            edges: components["schemas"]["PipelineEdge"][];
        };
        /** PipelineEdge */
        PipelineEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Conditional */
            conditional: boolean;
        };
        /** PipelineNode */
        PipelineNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            position: components["schemas"]["Position"];
        };
        /** Position */
        Position: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RetrievalEvent */
        RetrievalEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "retrieval";
            /** Stage */
            stage: string;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["Retrieved"][];
        };
        /** Retrieved */
        Retrieved: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "help_section" | "ticket";
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Status */
            status?: ("open" | "resolved") | null;
            /** Score */
            score: number;
        };
        /** ScorecardEntry */
        ScorecardEntry: {
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
            /** Profile */
            profile: string | null;
            /** Role */
            role: string | null;
            /** Model */
            model: string | null;
            /** With Retrieval */
            with_retrieval: boolean | null;
            /** Routing Accuracy */
            routing_accuracy: number | null;
            /** Verdict Accuracy */
            verdict_accuracy: number | null;
            /** Retrieval Hit Rate */
            retrieval_hit_rate: number | null;
            /** Cost Per Ticket */
            cost_per_ticket: number | null;
            /** P50 Latency S */
            p50_latency_s: number | null;
        };
        /** Series */
        Series: {
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
        };
        /** SeriesOut */
        SeriesOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "series";
            /** Query */
            query: string;
            /** Unit */
            unit?: string | null;
            /** Series */
            series: components["schemas"]["Series"][];
        };
        /** SeriesPoint */
        SeriesPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Value */
            value: number;
        };
        /** SimulatorTemplate */
        SimulatorTemplate: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Expected Route */
            expected_route?: string | null;
            /** Setup */
            setup?: string | null;
        };
        /** SimulatorTicketIn */
        SimulatorTicketIn: {
            /** Template Id */
            template_id?: string | null;
            /** Subject */
            subject?: string | null;
            /** Body */
            body?: string | null;
            /**
             * Tenant Id
             * @default figma-merch
             */
            tenant_id: string;
            /**
             * Requester
             * @default ops@figma-merch.example
             */
            requester: string | null;
        };
        /** Span */
        Span: {
            /** Span Id */
            span_id: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Service */
            service: string;
            /** Name */
            name: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Status
             * @default unset
             * @enum {string}
             */
            status: "ok" | "error" | "unset";
            /**
             * Attributes
             * @default {}
             */
            attributes: {
                [key: string]: unknown;
            };
        };
        /**
         * StageEvent
         * @description Drives the pipeline nodes.
         */
        StageEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stage";
            /** Stage */
            stage: string;
            /**
             * Status
             * @enum {string}
             */
            status: "waiting" | "running" | "done" | "skipped" | "failed";
            /** Summary */
            summary?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /**
         * StoredEvent
         * @description An event as the API returns it: the row id and timestamp around the payload.
         */
        StoredEvent: {
            /** Id */
            id: number;
            /** Ticket Id */
            ticket_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Event */
            event: components["schemas"]["StageEvent"] | components["schemas"]["ToolCallEvent"] | components["schemas"]["ModelDeltaEvent"] | components["schemas"]["ModelOutputEvent"] | components["schemas"]["RetrievalEvent"] | components["schemas"]["JevEvent"] | components["schemas"]["ApprovalRequiredEvent"] | components["schemas"]["LinkEvent"] | components["schemas"]["DeliveryEvent"] | components["schemas"]["OutcomeEvent"] | components["schemas"]["ErrorEvent"];
        };
        /** TableOut */
        TableOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "table";
            /** Columns */
            columns: string[];
            /** Rows */
            rows: unknown[][];
        };
        /** TerminalOut */
        TerminalOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "terminal";
            /** Command */
            command: string;
            /** Output */
            output: string;
            /**
             * Exit Code
             * @default 0
             */
            exit_code: number;
        };
        /** TicketDetail */
        TicketDetail: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string | null;
            /** Subject */
            subject: string;
            /** Requester */
            requester: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "needs_approval" | "done" | "failed";
            /** Lane */
            lane: string | null;
            /** Current Stage */
            current_stage: string | null;
            /** Stages Done */
            stages_done: number;
            /** Severity */
            severity: number | null;
            /** Verdict Kind */
            verdict_kind: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Completed At */
            completed_at: string | null;
            /** Body */
            body: string;
            jev?: components["schemas"]["JevEvent"] | null;
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["LinkEvent"][];
            pending_approval?: components["schemas"]["ApprovalRequiredEvent"] | null;
            outcome?: components["schemas"]["OutcomeEvent"] | null;
            /** Stages Total */
            readonly stages_total: number;
        };
        /**
         * TicketSummary
         * @description One row of the queue. Built straight from a TicketRow (from_attributes).
         */
        TicketSummary: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string | null;
            /** Subject */
            subject: string;
            /** Requester */
            requester: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "needs_approval" | "done" | "failed";
            /** Lane */
            lane: string | null;
            /** Current Stage */
            current_stage: string | null;
            /** Stages Done */
            stages_done: number;
            /** Severity */
            severity: number | null;
            /** Verdict Kind */
            verdict_kind: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Completed At */
            completed_at: string | null;
            /** Stages Total */
            readonly stages_total: number;
        };
        /**
         * ToolCallEvent
         * @description One tool call or shell command. Sent twice: status=running, then ok/error with output.
         */
        ToolCallEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "tool_call";
            /** Stage */
            stage: string;
            /** Call Id */
            call_id: string;
            /** Tool */
            tool: string;
            /**
             * Args
             * @default {}
             */
            args: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "ok" | "error";
            /** Duration Ms */
            duration_ms?: number | null;
            /** Output */
            output?: (components["schemas"]["CodeOut"] | components["schemas"]["DiffOut"] | components["schemas"]["TerminalOut"] | components["schemas"]["CommitOut"] | components["schemas"]["LogOut"] | components["schemas"]["SeriesOut"] | components["schemas"]["TraceOut"] | components["schemas"]["TableOut"] | components["schemas"]["JsonOut"]) | null;
        };
        /** TraceOut */
        TraceOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            render: "trace";
            /** Trace Id */
            trace_id: string;
            /** Url */
            url?: string | null;
            /** Spans */
            spans: components["schemas"]["Span"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    pylon_webhook_webhooks_pylon_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_tickets_tickets_get: {
        parameters: {
            query?: {
                status?: ("queued" | "running" | "needs_approval" | "done" | "failed") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
        };
    };
    approve_tickets__ticket_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_tickets__ticket_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_tickets__ticket_id__events_stream_get: {
        parameters: {
            query?: {
                replay?: boolean;
            };
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulator_templates_simulator_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorTemplate"][];
                };
            };
        };
    };
    simulator_send_simulator_tickets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulatorTicketIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scorecard_evals_scorecard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorecardEntry"][];
                };
            };
        };
    };
}
