"""The code indexer's extraction (app/indexer/extract.py): symbols, error messages, flag reads and
gRPC handlers from source text, on snippets shaped like the shop's own code. No git, no database."""

import re
import shutil
import tempfile
from pathlib import Path

import pytest

from app.indexer import extract

CHARGE_JS = """\
const { OpenFeature } = require('@openfeature/server-sdk');

module.exports.charge = async request => {
  const numberVariant = await OpenFeature.getClient().getNumberValue("paymentFailure", 0);
  if (!valid) {
    throw new Error('Credit card info is invalid.');
  }
  if (currentPeriod >= expiryPeriod) {
    throw new Error(`The credit card (ending ${lastFourDigits}) expired on ${month}/${year}.`);
  }
};

function luhn(number) {
  return true;
}
"""

INDEX_JS = """\
const charge = require('./charge')

async function chargeServiceHandler(call, callback) {
  try {
    callback(null, await charge.charge(call.request))
  } catch (err) {
    logger.warn({ err }, 'Charge declined.')
    callback(err)
  }
}

server.addService(health.service, new health.Implementation({}))
server.addService(otelDemoPackage.oteldemo.PaymentService.service, { charge: chargeServiceHandler })
"""

CHECKOUT_GO = """\
package main

type checkout struct {
	cartSvcAddr string
}

func (cs *checkout) PlaceOrder(ctx context.Context, req *pb.PlaceOrderRequest) (*pb.Resp, error) {
	if flags.PaymentUnreachable.Value(ctx, openfeature.EvaluationContext{}) {
		return nil, status.Errorf(codes.Internal, "failed to charge card: %+v", err)
	}
	logger.Error(fmt.Sprintf("Failed to prepare OpAMP identity: %v", err))
	return nil, fmt.Errorf("cart failure: %+v", err)
}

func mustMapEnv(target *string, key string) {
	panic(errors.New("environment variable not set"))
}
"""

FLAGS_GEN_GO = """\
// Code generated by OpenFeature CLI. DO NOT EDIT.
package flags

var PaymentUnreachable = struct {
	fmt.Stringer
	Value evaluationValue[bool]
}{
	Stringer: stringer("paymentUnreachable"),
}

var EmitRawPii = struct {
	fmt.Stringer
}{
	Stringer: stringer("emitRawPii"),
}
"""

ROUTES_PHP = """\
<?php
function calculateQuote($jsonObject): float
{
    if (!array_key_exists('numberOfItems', $jsonObject)) {
        throw new \\InvalidArgumentException('numberOfItems not provided');
    }
    return 1.0;
}

class QuoteService {
    public function quote(int $items): float { return $items * 8.99; }
}
"""

CART_CS = """\
namespace cart.services;

public class CartService : Oteldemo.CartService.CartServiceBase
{
    public override async Task<Empty> AddItem(AddItemRequest request, ServerCallContext context)
    {
        var rate = await _featureFlagHelper.GetDoubleValueAsync("cartFailure", 0);
        throw new RpcException(
            new Status(StatusCode.FailedPrecondition, $"Can't access cart storage. {ex}"));
    }

    private void Connect()
    {
        throw new ApplicationException("Wasn't able to connect to redis");
    }
}

internal static partial class Log
{
    [LoggerMessage(Level = LogLevel.Error, Message = "Redis connection failed for {userId}")]
    public static partial void RedisConnectionFailed(ILogger logger, string userId);

    [LoggerMessage(Level = LogLevel.Debug, Message = "Performing small test")]
    public static partial void RedisSmallTest(ILogger logger);
}

public interface ICartStore
{
    Task AddItemAsync(string userId, string productId, int quantity);
}
"""

PROTO = """\
syntax = "proto3";
service CartService {
    rpc AddItem(AddItemRequest) returns (Empty) {}
    rpc GetCart(GetCartRequest) returns (Cart) {}
}
service PaymentService {
    rpc Charge(ChargeRequest) returns (ChargeResponse) {}
}
service CheckoutService {
    rpc PlaceOrder(PlaceOrderRequest) returns (PlaceOrderResponse) {}
}
"""


def line_of(source: str, text: str) -> int:
    return next(i for i, line in enumerate(source.splitlines(), 1) if text in line)


def test_languages_come_from_file_extensions():
    assert extract.language("src/payment/charge.js") == "javascript"
    assert extract.language("src/checkout/main.go") == "go"
    assert extract.language("src/quote/app/routes.php") == "php"
    assert extract.language("src/cart/src/services/CartService.cs") == "csharp"
    assert extract.language("src/payment/package.json") is None


def test_javascript_symbols():
    found = {(s.name, s.kind, s.line) for s in extract.symbols("x.js", CHARGE_JS, "javascript")}
    assert ("charge", "function", line_of(CHARGE_JS, "module.exports.charge")) in found
    assert ("luhn", "function", line_of(CHARGE_JS, "function luhn")) in found
    handler = extract.symbols("index.js", INDEX_JS, "javascript")[0]
    assert handler.name == "chargeServiceHandler"
    assert handler.signature == "async function chargeServiceHandler(call, callback)"


def test_go_symbols_carry_receivers_and_signatures():
    found = {s.name: s for s in extract.symbols("main.go", CHECKOUT_GO, "go")}
    assert found["checkout"].kind == "struct"
    place = found["PlaceOrder"]
    assert place.kind == "method" and place.line == line_of(CHECKOUT_GO, "PlaceOrder(")
    assert place.signature.startswith("func (cs *checkout) PlaceOrder(ctx context.Context")
    assert "{" not in place.signature
    assert found["mustMapEnv"].kind == "function"


def test_php_symbols():
    found = {(s.name, s.kind) for s in extract.symbols("routes.php", ROUTES_PHP, "php")}
    assert {("calculateQuote", "function"), ("QuoteService", "class"), ("quote", "method")} <= found


@pytest.mark.parametrize(
    ("file", "source", "lang", "text"),
    [
        ("charge.js", CHARGE_JS, "javascript", "Credit card info is invalid."),
        (
            "charge.js",
            CHARGE_JS,
            "javascript",
            "The credit card (ending ${lastFourDigits}) expired on ${month}/${year}.",
        ),
        ("index.js", INDEX_JS, "javascript", "Charge declined."),
        ("main.go", CHECKOUT_GO, "go", "failed to charge card: %+v"),
        ("main.go", CHECKOUT_GO, "go", "Failed to prepare OpAMP identity: %v"),
        ("main.go", CHECKOUT_GO, "go", "cart failure: %+v"),
        ("main.go", CHECKOUT_GO, "go", "environment variable not set"),
        ("CartService.cs", CART_CS, "csharp", "Can't access cart storage. {ex}"),
        ("CartService.cs", CART_CS, "csharp", "Wasn't able to connect to redis"),
        ("CartService.cs", CART_CS, "csharp", "Redis connection failed for {userId}"),
        ("routes.php", ROUTES_PHP, "php", "numberOfItems not provided"),
    ],
    ids=lambda v: v if isinstance(v, str) and len(v) < 40 and "\n" not in v else None,
)
def test_error_messages_are_found_with_their_line(file, source, lang, text):
    found = {(e.text, e.line) for e in extract.error_strings(file, source, lang)}
    assert (text, line_of(source, text.split("$")[0].split("%")[0])) in found


def test_only_literal_messages_are_kept():
    source = "function f() { throw new Error(message); throw err; }"
    assert extract.error_strings("x.js", source, "javascript") == []


@pytest.mark.parametrize(
    ("template", "seen"),
    [
        (
            "The credit card (ending ${lastFourDigits}) expired on ${month}/${year}.",
            "rpc error: desc = The credit card (ending 4242) expired on 9/2026.",
        ),
        ("failed to charge card: %+v", "failed to charge card: could not charge the card"),
        ("numberOfItems not provided", "numberOfItems not provided"),
    ],
)
def test_a_template_matches_the_message_it_produces(template, seen):
    assert re.search(extract.template_pattern(template), seen)


def test_a_template_does_not_match_other_messages():
    pattern = extract.template_pattern("The credit card (ending ${n}) expired on ${m}/${y}.")
    assert not re.search(pattern, "Sorry, we cannot process amex credit cards.")


def test_csharp_symbols():
    found = {(s.name, s.kind) for s in extract.symbols("c.cs", CART_CS, "csharp")}
    assert {("CartService", "class"), ("AddItem", "method"), ("ICartStore", "interface")} <= found
    [add] = [s for s in extract.symbols("c.cs", CART_CS, "csharp") if s.name == "AddItem"]
    assert add.signature.startswith("public override async Task<Empty> AddItem(AddItemRequest")


def test_csharp_debug_logs_are_not_errors():
    texts = {e.text for e in extract.error_strings("c.cs", CART_CS, "csharp")}
    assert "Performing small test" not in texts


def test_csharp_flag_reads_and_grpc_handlers():
    assert [f.flag for f in extract.flag_reads("c.cs", CART_CS, "csharp", {})] == ["cartFailure"]
    rpcs = extract.rpc_handlers({"src/cart/c.cs": CART_CS}, extract.proto_methods(PROTO))
    assert [(r.method, r.line) for r in rpcs] == [
        ("CartService/AddItem", line_of(CART_CS, "Task<Empty> AddItem"))
    ]


def test_a_csharp_placeholder_matches_what_it_produces():
    pattern = extract.template_pattern("Can't access cart storage. {ex}")
    assert re.search(
        pattern, "Can't access cart storage. StackExchange.Redis.RedisTimeoutException"
    )


def test_a_template_is_a_posix_pattern_for_the_codebox_awk():
    pattern = extract.template_pattern("Order #${id} failed: 50% [retry] (a|b)")
    assert pattern == r"Order #.* failed: 50% \[retry] \(a\|b\)"
    assert re.search(pattern, "Order #12 failed: 50% [retry] (a|b)")


def test_a_template_that_is_mostly_placeholders_matches_nothing():
    assert extract.template_pattern("%v: %v") == ""
    assert extract.template_pattern("${err}") == ""


def test_flag_reads_in_javascript_and_go():
    js = extract.flag_reads("charge.js", CHARGE_JS, "javascript", {})
    assert [(f.flag, f.line) for f in js] == [
        ("paymentFailure", line_of(CHARGE_JS, "paymentFailure"))
    ]
    keys = extract.go_flag_keys(FLAGS_GEN_GO)
    assert keys == {"PaymentUnreachable": "paymentUnreachable", "EmitRawPii": "emitRawPii"}
    go = extract.flag_reads("main.go", CHECKOUT_GO, "go", keys)
    assert [(f.flag, f.line) for f in go] == [
        ("paymentUnreachable", line_of(CHECKOUT_GO, "PaymentUnreachable"))
    ]


def test_proto_methods():
    assert extract.proto_methods(PROTO) == [
        "CartService/AddItem",
        "CartService/GetCart",
        "PaymentService/Charge",
        "CheckoutService/PlaceOrder",
    ]


def test_grpc_handlers_in_javascript_and_go():
    methods = extract.proto_methods(PROTO)
    files = {"src/payment/index.js": INDEX_JS, "src/checkout/main.go": CHECKOUT_GO}
    found = {(r.method, r.file, r.line) for r in extract.rpc_handlers(files, methods)}
    assert found == {
        (
            "PaymentService/Charge",
            "src/payment/index.js",
            line_of(INDEX_JS, "async function chargeServiceHandler"),
        ),
        ("CheckoutService/PlaceOrder", "src/checkout/main.go", line_of(CHECKOUT_GO, "PlaceOrder(")),
    }


def test_generated_and_test_files_are_skipped():
    assert extract.is_source("src/checkout/main.go", CHECKOUT_GO)
    assert not extract.is_source("src/checkout/flags/flags_gen.go", FLAGS_GEN_GO)
    assert not extract.is_source("src/checkout/main_test.go", "package main")
    assert not extract.is_source("src/payment/node_modules/x/index.js", "")
    assert not extract.is_source("src/checkout/genproto/demo.pb.go", "package oteldemo")


def test_go_clients_are_not_handlers():
    """checkout calls the email service through its own sendOrderConfirmation(ctx, *pb...);
    a Go server's handler has the proto's exact, exported name."""
    client = (
        "package main\n"
        "func (cs *checkout) sendOrderConfirmation(ctx context.Context,\n"
        "\treq *pb.SendOrderConfirmationRequest) error {\n"
        "\treturn nil\n}\n"
    )
    proto = "service EmailService {\n  rpc SendOrderConfirmation(Req) returns (Empty) {}\n}\n"
    assert (
        extract.rpc_handlers({"src/checkout/main.go": client}, extract.proto_methods(proto)) == []
    )


# --- building, exporting, service cards --------------------------------------------------------

from app.indexer import build, card, export  # noqa: E402

FILES = {
    "src/payment/charge.js": CHARGE_JS,
    "src/payment/index.js": INDEX_JS,
    "src/payment/charge.test.js": "throw new Error('only in a test')",
    "src/payment/package.json": "{}",
}


def payment_index() -> build.CodeIndex:
    return build.build_index("payment", "f" * 40, FILES, PROTO)


def test_an_index_holds_one_service_at_one_commit():
    index = payment_index()
    assert index.service == "payment" and index.git_sha == "f" * 40
    assert {s.file for s in index.symbols} == {"src/payment/charge.js", "src/payment/index.js"}
    assert "only in a test" not in {e.text for e in index.errors}
    assert [(r.method, r.file) for r in index.rpcs] == [
        ("PaymentService/Charge", "src/payment/index.js")
    ]
    assert [f.flag for f in index.flags] == ["paymentFailure"]
    assert set(index.files) == {"src/payment/charge.js", "src/payment/index.js"}


def test_go_flag_keys_come_from_the_generated_file():
    files = {"src/checkout/main.go": CHECKOUT_GO, "src/checkout/flags/flags_gen.go": FLAGS_GEN_GO}
    index = build.build_index("checkout", "e" * 40, files, PROTO)
    assert [f.flag for f in index.flags] == ["paymentUnreachable"]
    assert "src/checkout/flags/flags_gen.go" not in {s.file for s in index.symbols}


def test_the_export_is_what_the_helper_commands_read(tmp_path):
    export.write(tmp_path, [payment_index()], {"payment": "# payment\nCharges cards."})
    symbols = [line.split("\t") for line in (tmp_path / "symbols.tsv").read_text().splitlines()]
    assert ["src/payment/index.js", "3", "payment", "function", "chargeServiceHandler"] == (
        next(s for s in symbols if s[4] == "chargeServiceHandler")[:5]
    )
    errors = [line.split("\t") for line in (tmp_path / "errors.tsv").read_text().splitlines()]
    expired = next(e for e in errors if "expired on" in e[3])
    assert expired[:3] == [
        "src/payment/charge.js",
        str(line_of(CHARGE_JS, "expired on")),
        "payment",
    ]
    assert re.search(expired[4], "The credit card (ending 4242) expired on 9/2026.")
    assert (
        (tmp_path / "rpc.tsv")
        .read_text()
        .startswith("PaymentService/Charge\tsrc/payment/index.js\t")
    )
    assert "paymentFailure\tsrc/payment/charge.js\t" in (tmp_path / "flags.tsv").read_text()
    assert (tmp_path / "cards" / "payment.md").read_text().startswith("# payment")


def test_the_export_keeps_one_record_per_line(tmp_path):
    index = payment_index()
    index.errors.append(extract.ErrorString("src/payment/x.js", 1, "two\tcolumns\nand lines"))
    export.write(tmp_path, [index], {})
    lines = (tmp_path / "errors.tsv").read_text().splitlines()
    assert all(len(line.split("\t")) == 5 for line in lines)


def test_the_export_is_readable_by_the_codebox_user():
    """The codebox runs as its own user, and mkdtemp makes a directory only its owner can read."""
    out = Path(tempfile.mkdtemp())
    try:
        export.write(out, [payment_index()], {"payment": "# payment"})
        for path in [out, *out.rglob("*")]:
            other = path.stat().st_mode & 0o007
            assert other == (0o005 if path.is_dir() else 0o004), path
    finally:
        shutil.rmtree(out)


async def test_a_service_card_is_written_from_the_code(monkeypatch):
    seen = {}

    async def fake_run(prompt: str) -> card.ServiceCard:
        seen["prompt"] = prompt
        return card.ServiceCard(
            purpose="Charges cards.",
            entry_points=["PaymentService/Charge: src/payment/index.js:3"],
            business_rules=["Only Visa and Mastercard are accepted."],
            dependencies=["flagd"],
            error_messages=[
                card.ErrorMeaning(message="Credit card info is invalid.", meaning="Bad number."),
                card.ErrorMeaning(message="Made up by the model.", meaning="?"),
            ],
        )

    monkeypatch.setattr(card, "_run", fake_run)
    text = await card.write_card(payment_index(), "Validates and charges cards.")
    assert "src/payment/charge.js" in seen["prompt"]
    assert f"{line_of(CHARGE_JS, 'expired on')}: " in seen["prompt"]  # the code has line numbers
    assert "PaymentService/Charge -> src/payment/index.js" in seen["prompt"]
    assert text.startswith("# payment at ffffffff")
    assert "Only Visa and Mastercard are accepted." in text
    assert "Credit card info is invalid." in text
    assert "Made up by the model." not in text  # only messages the code really has
