"""initial schema

Tables are autogenerated from app/tables.py. Written by hand: the pgvector extension and the
NOTIFY trigger on events, which the console's live stream listens to.

Revision ID: 0001
Revises:
Create Date: 2026-09-26 00:46:40.550016
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


NOTIFY_FUNCTION = """
CREATE FUNCTION notify_event() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('ticket_events', NEW.ticket_id || ':' || NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql
"""
NOTIFY_TRIGGER = """
CREATE TRIGGER events_notify AFTER INSERT ON events
  FOR EACH ROW EXECUTE FUNCTION notify_event()
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "code_symbols",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("git_sha", sa.Text(), nullable=False),
        sa.Column("file", sa.Text(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_symbols")),
    )
    op.create_index(
        op.f("ix_code_symbols_git_sha_name"), "code_symbols", ["git_sha", "name"], unique=False
    )
    op.create_index(
        op.f("ix_code_symbols_service_git_sha"),
        "code_symbols",
        ["service", "git_sha"],
        unique=False,
    )
    op.create_table(
        "deploys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("previous_version", sa.Text(), nullable=True),
        sa.Column("git_sha", sa.Text(), nullable=True),
        sa.Column(
            "commit_titles", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "deployed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deploys")),
    )
    op.create_index(op.f("ix_deploys_deployed_at"), "deploys", ["deployed_at"], unique=False)
    op.create_table(
        "error_strings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("git_sha", sa.Text(), nullable=False),
        sa.Column("file", sa.Text(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_error_strings")),
    )
    op.create_index(op.f("ix_error_strings_git_sha"), "error_strings", ["git_sha"], unique=False)
    op.create_table(
        "eval_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("profile", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("with_retrieval", sa.Boolean(), nullable=True),
        sa.Column("routing_accuracy", sa.Double(), nullable=True),
        sa.Column("verdict_accuracy", sa.Double(), nullable=True),
        sa.Column("retrieval_hit_rate", sa.Double(), nullable=True),
        sa.Column("cost_per_ticket", sa.Double(), nullable=True),
        sa.Column("p50_latency_s", sa.Double(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_results")),
    )
    op.create_table(
        "flag_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flag", sa.Text(), nullable=False),
        sa.Column("old_variant", sa.Text(), nullable=True),
        sa.Column("new_variant", sa.Text(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flag_changes")),
    )
    op.create_index(
        op.f("ix_flag_changes_changed_at"), "flag_changes", ["changed_at"], unique=False
    )
    op.create_table(
        "flag_reads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("git_sha", sa.Text(), nullable=False),
        sa.Column("flag", sa.Text(), nullable=False),
        sa.Column("file", sa.Text(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flag_reads")),
    )
    op.create_index(
        op.f("ix_flag_reads_git_sha_flag"), "flag_reads", ["git_sha", "flag"], unique=False
    )
    op.create_table(
        "retrieval_docs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("service", sa.Text(), nullable=True),
        sa.Column("version", sa.Text(), nullable=True),
        sa.Column("verdict", sa.Text(), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("linear_issue", sa.Text(), nullable=True),
        sa.Column("tenant", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, '') || ' ' || coalesce(summary, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('help_section', 'ticket')", name=op.f("ck_retrieval_docs_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_docs")),
    )
    op.create_index(
        op.f("ix_retrieval_docs_embedding"),
        "retrieval_docs",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_retrieval_docs_kind_status"), "retrieval_docs", ["kind", "status"], unique=False
    )
    op.create_index(
        op.f("ix_retrieval_docs_tsv"),
        "retrieval_docs",
        ["tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "rpc_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("git_sha", sa.Text(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("handler_file", sa.Text(), nullable=False),
        sa.Column("handler_line", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rpc_map")),
    )
    op.create_index(
        op.f("ix_rpc_map_git_sha_method"), "rpc_map", ["git_sha", "method"], unique=False
    )
    op.create_table(
        "service_cards",
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("git_sha", sa.Text(), nullable=False),
        sa.Column("card", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("service", "git_sha", name=op.f("pk_service_cards")),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("plan", sa.Text(), nullable=True),
        sa.Column("user_prefix", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), server_default="pylon", nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("requester", sa.Text(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("lane", sa.Text(), nullable=True),
        sa.Column("current_stage", sa.Text(), nullable=True),
        sa.Column("stages_done", sa.Integer(), server_default="0", nullable=False),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column("verdict_kind", sa.Text(), nullable=True),
        sa.Column(
            "cost_usd", sa.Numeric(precision=10, scale=4), server_default="0", nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'needs_approval', 'done', 'failed')",
            name=op.f("ck_tickets_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tickets_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index(
        op.f("ix_tickets_status_received_at"), "tickets", ["status", "received_at"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ticket_id", sa.Text(), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_events_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_ticket_id_id"), "events", ["ticket_id", "id"], unique=False)
    op.create_table(
        "investigations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Text(), nullable=True),
        sa.Column("service", sa.Text(), nullable=True),
        sa.Column("version", sa.Text(), nullable=True),
        sa.Column("error_signature", sa.Text(), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("file_line", sa.Text(), nullable=True),
        sa.Column("linear_issue", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'resolved')", name=op.f("ck_investigations_status")),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_investigations_ticket_id_tickets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigations")),
    )
    op.create_index(
        op.f("ix_investigations_service_version_error_signature"),
        "investigations",
        ["service", "version", "error_signature"],
        unique=False,
    )
    op.create_table(
        "verdicts",
        sa.Column("ticket_id", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_verdicts_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ticket_id", name=op.f("pk_verdicts")),
    )
    op.execute(NOTIFY_FUNCTION)
    op.execute(NOTIFY_TRIGGER)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS events_notify ON events")
    op.execute("DROP FUNCTION IF EXISTS notify_event()")
    op.drop_table("verdicts")
    op.drop_index(
        op.f("ix_investigations_service_version_error_signature"), table_name="investigations"
    )
    op.drop_table("investigations")
    op.drop_index(op.f("ix_events_ticket_id_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_tickets_status_received_at"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_table("tenants")
    op.drop_table("service_cards")
    op.drop_index(op.f("ix_rpc_map_git_sha_method"), table_name="rpc_map")
    op.drop_table("rpc_map")
    op.drop_index(
        op.f("ix_retrieval_docs_tsv"), table_name="retrieval_docs", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_retrieval_docs_kind_status"), table_name="retrieval_docs")
    op.drop_index(
        op.f("ix_retrieval_docs_embedding"),
        table_name="retrieval_docs",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("retrieval_docs")
    op.drop_index(op.f("ix_flag_reads_git_sha_flag"), table_name="flag_reads")
    op.drop_table("flag_reads")
    op.drop_index(op.f("ix_flag_changes_changed_at"), table_name="flag_changes")
    op.drop_table("flag_changes")
    op.drop_table("eval_results")
    op.drop_index(op.f("ix_error_strings_git_sha"), table_name="error_strings")
    op.drop_table("error_strings")
    op.drop_index(op.f("ix_deploys_deployed_at"), table_name="deploys")
    op.drop_table("deploys")
    op.drop_index(op.f("ix_code_symbols_service_git_sha"), table_name="code_symbols")
    op.drop_index(op.f("ix_code_symbols_git_sha_name"), table_name="code_symbols")
    op.drop_table("code_symbols")
    # The vector extension stays: other database objects may use it.
