"""Write reproducible, clearly synthetic ticket memory from reviewed scenario templates."""

import json
from pathlib import Path

TOPICS = [
    # subject, symptom, service, type, verdict, root cause, resolution, near-miss group
    (
        "Which payment cards are accepted?",
        "Shoppers ask whether Visa, Mastercard, or Amex can be used at checkout.",
        "payment",
        "how_to",
        None,
        "Card-type policy allows Visa and Mastercard.",
        "Explained the accepted card types.",
        "card-decline",
    ),
    (
        "Amex card refused at checkout",
        "A valid Amex card was declined although the shopper believed any credit card would work.",
        "payment",
        "tech_issue",
        "false_positive",
        "Amex is outside the allowed card types.",
        "Explained the Visa and Mastercard rule.",
        "card-decline",
    ),
    (
        "Card expiry month question",
        "A shopper asks whether a card with this month's printed expiry should remain valid.",
        "payment",
        "how_to",
        None,
        "The baseline expiry rule allows the printed month.",
        "Explained the expiry-month rule.",
        "card-decline",
    ),
    (
        "Bulk shipping quote higher than expected",
        "A twenty-item shipment was quoted much higher than a small order.",
        "quote",
        "tech_issue",
        "confirmed_bug",
        "A historical quote configuration duplicated the per-item charge.",
        "Corrected the older quote configuration.",
        "shipping-total",
    ),
    (
        "One in four payments failed",
        "Approximately a quarter of checkout attempts failed after a flag change.",
        "payment",
        "tech_issue",
        "config_incident",
        "A historical paymentFailure flag variant was enabled.",
        "Reset the flag to off.",
        "card-decline",
    ),
    (
        "Cart still shows items after a EUR order",
        "A shopper completed a euro order but saw old basket items on returning to the cart.",
        "checkout",
        "tech_issue",
        "confirmed_bug",
        "An older cleanup path skipped a non-USD basket.",
        "Restored cart cleanup in the earlier version.",
        "cart-state",
    ),
    (
        "Known product missing from the list",
        "A product could be fetched by ID but did not appear in browsing.",
        "product-catalog",
        "tech_issue",
        "confirmed_bug",
        "A historical catalog import left the listing incomplete.",
        "Rebuilt the older listing data.",
        "catalog-list",
    ),
    (
        "How are EUR prices calculated?",
        "A shopper asks why product and shipping amounts appear in euros rather than catalog USD.",
        "checkout",
        "how_to",
        None,
        "Checkout converts product and shipping prices to the selected currency.",
        "Explained selected-currency conversion.",
        "amount-display",
    ),
    (
        "Order confirmation email question",
        "A completed order has an ID but the shopper asks where the confirmation goes.",
        "checkout",
        "how_to",
        None,
        "Checkout sends the request to the entered email; the demo mailer is local.",
        "Explained sandbox email behavior.",
        "confirmation",
    ),
    (
        "Address form not submitted",
        "The shopper left a required country or ZIP field blank and cannot submit checkout.",
        "checkout",
        "tech_issue",
        "false_positive",
        "The browser form requires shipping address fields.",
        "Asked the shopper to complete the fields.",
        "shipping-address",
    ),
    (
        "How to clear the entire cart",
        "The shopper wants to discard all items before paying.",
        "cart",
        "how_to",
        None,
        "The cart page provides Empty Cart.",
        "Pointed to the Empty Cart action.",
        "cart-state",
    ),
    (
        "Where is the shipping tracking ID?",
        "A customer has an order ID and asks for the shipment tracking identifier.",
        "checkout",
        "how_to",
        None,
        "Shipping returns a tracking ID in the completed order.",
        "Explained where the tracking ID appears.",
        "confirmation",
    ),
    (
        "Catalog product picture is missing",
        "A product name and price appear but its cart picture does not render.",
        "product-catalog",
        "tech_issue",
        "inconclusive",
        "The picture reference or storefront image may be missing.",
        "Requested the product ID for investigation.",
        "catalog-list",
    ),
    (
        "Malformed Visa number rejected",
        "A shopper entered a Visa number with a missing digit and got invalid card information.",
        "payment",
        "tech_issue",
        "false_positive",
        "Payment validates the card number before charging.",
        "Asked the shopper to verify the entered number.",
        "card-decline",
    ),
    (
        "Cart became unavailable briefly",
        "Cart reads failed for several shoppers during a flag exercise.",
        "cart",
        "tech_issue",
        "config_incident",
        "A historical cartFailure flag was enabled.",
        "Disabled the test flag.",
        "cart-state",
    ),
    (
        "Why does the order total differ?",
        "A shopper compares a USD product page with an order total in another currency.",
        "checkout",
        "how_to",
        None,
        "Checkout localizes prices and includes shipping.",
        "Explained currency and shipping components.",
        "amount-display",
    ),
    (
        "How is a shipping estimate made?",
        "A team wants to know whether quantity affects the quote before payment.",
        "quote",
        "how_to",
        None,
        "Shipping sends total item quantity to the quote service.",
        "Explained per-item quote calculation.",
        "shipping-total",
    ),
    (
        "Can a customer pay with Visa?",
        "A buyer asks whether an ordinary valid Visa card works at checkout.",
        "payment",
        "how_to",
        None,
        "Visa is in the payment card-type allowlist.",
        "Confirmed the accepted type.",
        "card-decline",
    ),
    (
        "Can a customer pay with Mastercard?",
        "A buyer asks whether an ordinary valid Mastercard works at checkout.",
        "payment",
        "how_to",
        None,
        "Mastercard is in the payment card-type allowlist.",
        "Confirmed the accepted type.",
        "card-decline",
    ),
    (
        "Request to add Apple Pay",
        "A merchant asks for Apple Pay alongside the existing card form.",
        "checkout",
        "request",
        None,
        "The current checkout form offers card fields, not Apple Pay.",
        "Logged a payment-method feature request.",
        "payment-method-request",
    ),
]

OPENINGS = [
    "Our support team received this question:",
    "A shopper wrote to us:",
    "We saw the following report:",
    "An account manager passed along this note:",
    "During checkout review, the merchant said:",
    "A customer asked about the shop:",
    "The storefront team received a report:",
    "One earlier ticket described this:",
    "The merchant asked for help with this:",
    "A previous conversation recorded:",
]
ENDINGS = [
    "Please clarify what the shop is meant to do.",
    "Can support check the behavior and explain it?",
    "The merchant wants a short answer with the relevant details.",
    "They need to know whether engineering should investigate.",
    "Please review the customer-visible result.",
    "They would like the next support step.",
    "The issue was reported without any card secrets.",
    "They asked us to compare it with earlier reports.",
    "Can this be explained from the shop behavior?",
    "Support needs a concise resolution for the shopper.",
]


def build() -> list[dict]:
    rows = []
    for topic_number, (
        subject,
        symptom,
        service,
        ticket_type,
        verdict,
        root_cause,
        resolution,
        group,
    ) in enumerate(TOPICS, start=1):
        for variant in range(1, 11):
            rows.append(
                {
                    "id": f"SYN-{topic_number:02d}-{variant:02d}",
                    "subject": subject if variant == 1 else f"{subject} — follow-up {variant}",
                    "body": f"{OPENINGS[variant - 1]} {symptom} {ENDINGS[variant - 1]}",
                    "summary": f"Symptom: {symptom}\nCause: {root_cause}\nResolution: {resolution}",
                    "type": ticket_type,
                    "service": service,
                    "verdict": verdict,
                    "root_cause": root_cause,
                    "status": "open" if ticket_type == "request" else "resolved",
                    "version": "v1.2.0"
                    if verdict in {"confirmed_bug", "config_incident"}
                    else None,
                    "linear_issue": None,
                    "tenant": "synthetic-demo",
                    "synthetic": True,
                    "near_miss_group": group,
                }
            )
    return rows


if __name__ == "__main__":
    path = Path(__file__).with_name("past_tickets.jsonl")
    path.write_text("".join(json.dumps(row, sort_keys=True) + "\n" for row in build()))
    print(f"wrote {len(build())} synthetic tickets to {path}")
